spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/intelligentdoorplate?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: public
    password: 123456
  mvc:
    format:
      date: yyyy-MM-dd
      hidden-method:
        filter:
          enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${file-upload-path}
server:
  servlet:
    encoding:
      charset: utf-8
  port: 8080
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.scu.intelligentdoorplateback.mapper: debug
file-upload-path: ./file
